- name: Desactivacion de proceso PatrolAgent
  become: yes
  become_user: patrol
  become_method: su
  become_exe: sudo su -
  shell: /patrol/Patrol3/scripts.d/S50PatrolAgent.sh stop
  register: status_baja

- name: Imprimir status de proceso PatrolAgent
  debug:
    msg: "{{ status_baja.stdout_lines }}"
 
