---
- name: Bloque de tareas 1
  block:
   - name: Accion 2
     become: yes
     become_method: sudo   
     shell: ssh -V
     register: salida_uno
     ignore_errors: yes

#- name: Bloque de tareas 2
#  block:
   - name: Accion 2  
     become: yes
     become_method: sudo   
     shell: echo "{{ ansible_hostname }},{{ ansible_os_family }},{{ansible_distribution_version}},{{ salida_uno.stderr.split()[0] }}" >> /tmp/out_openssh.csv
     delegate_to: asitsmaop2.awx.lab.net

- name: Bloque de tareas 2
  block:
   - name: Accion 2
     host: asitsmaop2.awx.lab.net
     #become: yes
     #become_method: sudo 
     shell: cat /tmp/out_openssh.csv
     register: salida_dos
     #delegate_to: asitsmaop2.awx.lab.net

   - name: Resultado de la alta correcta de PatrolAgent en el remote Host "{{ ansible_facts['nodename'] }}"
     debug:
       msg:
        - "Salida del archivo:"
        - "{{ salida_dos.stdout }}"
        
#- name: Envio de corro desde los servidores de BAO
#  block:
#   - name: Accion 2  
#     mail:
#       host: 150.100.207.52
#       port: 25
#       to: juliocesar.hoyos.contractor@bbva.com
#       from: itoperationintegration.mx@bbva.com
#       subject: Validacion - Lista de equipos y version OpenSSH
#       body: Se anexa archivo de equipos con versiones de OpenSSH
#     delegate_to: asitsmaop1
