- name: Validacion pre-requisitos patrol
  block:
   - name: Informacion directorio patrol
     stat:
        path: /patrol
     register: directorio_pa     

   - name: Informacion usuario patrol
     getent:
       database: passwd
       key: patrol
     register: usuario_pa

   - name: Informacion grupo patrol
     getent:
       database: group
       key: grppatro
     register: grupo_pa

   - name: Resultado de la validacion de pre-requisitos de PatrolAgent en el remote Host.
     debug:
       msg: "{{ ansible_system }},{{ ansible_nodename }},OK,Cumple con todos los pre-requisidos"
     when: (directorio_pa.stat.uid == 1301 and directorio_pa.stat.gid == 1301) and (directorio_pa.stat.mode == 0755)

   - name: Resultado de la validacion de pre-requisitos de PatrolAgent en el remote Host.
     debug:
       msg: "{{ ansible_system }},{{ ansible_nodename }},No OK,No Cumple con todos los pre-requisidos"
     when: (directorio_pa.stat.uid != 1301 and directorio_pa.stat.gid != 1301) and (directorio_pa.stat.mode != 0755)
