---
- name: Bloque de descargar de las medias de Instalacion de PatrolAgent
  block:
   - name: Descarga media PatrolAgent AIX en el remote Host "{{ ansible_facts['nodename'] }}"
     become: yes
     become_method: sudo
     get_url:
       dest: /tmp/Base_AIX_Patrol_Without.tar.gz
       url: http://{{ websrvsimple }}:{{ websrvport }}/Base_Linux_Patrol_Without.tar.gz
       owner: patrol
       group: grppatro
       mode: 0754
       force_basic_auth: yes
     when: ansible_facts['os_family'] == "AIX"
   
   - name: Descarga media PatrolAgent Linux en el remote Host "{{ ansible_facts['nodename'] }}"
     become: yes
     become_method: sudo
     get_url:
       dest: /tmp/Base_Linux_Patrol_Without.tar.gz
       url: http://{{ websrvsimple }}:{{ websrvport }}/Base_Linux_Patrol_Without.tar.gz
       owner: patrol
       group: grppatro
       mode: 0754
       force_basic_auth: yes
     when: ansible_facts['system'] == "Linux"
    
   - name: Descarga media PatrolAgent Solaris en el remote Host "{{ ansible_facts['nodename'] }}"
     become: yes
     become_method: sudo
     get_url:   
       dest: /tmp/Base_Solaris_Patrol_Without.tar.gz
       url: http://{{ websrvsimple }}:{{ websrvport }}/Base_Solaris_Patrol_Without.tar.gz
       owner: patrol
       group: grppatro
       mode: 0754
       force_basic_auth: yes
     when: ansible_facts['os_family'] == "Solaris"
   
   - name: Validar permisos en el directorio patrol en el remote host "{{ ansible_facts['nodename'] }}"
     stat:
       path: /patrol/
     register: siperejcdirpa
   
   - name: Correccion de permisos al directorio /patrol antes de instalar en el remote Host "{{ ansible_facts['nodename'] }}"
     become: yes
     become_method: sudo
     file:
       path: /patrol/
       state: directory
       owner: patrol
       group: grppatro
       mode: 0755
     when: siperejcdirpa.stat.mode != "0755"
     
   - name: Cambiar permisos al Inslador PatrolAgent AIX en el remote Host "{{ ansible_facts['nodename'] }}"
     become: yes
     become_method: sudo
     file:
       path: /tmp/Base_{{ ansible_facts['os_family'] }}_Patrol_Without.tar.gz
       owner: patrol
       group: grppatro
       mode: 0754
     when: ansible_facts['os_family'] == "AIX"

   - name: Cambiar permisos al Inslador PatrolAgent Linux en el remote Host "{{ ansible_facts['nodename'] }}"
     become: yes
     become_method: sudo
     file:
       path: /tmp/Base_{{ ansible_facts['system'] }}_Patrol_Without.tar.gz
       owner: patrol
       group: grppatro
       mode: 0754
     when: ansible_facts['system'] == "Linux"
     
   - name: Cambiar permisos al Inslador PatrolAgent Solaris en el remote Host "{{ ansible_facts['nodename'] }}"
     become: yes
     become_method: sudo
     file:
       path: /tmp/Base_{{ ansible_facts['os_family'] }}_Patrol_Without.tar.gz
       owner: patrol
       group: grppatro
       mode: 0754
     when: ansible_facts['os_family'] == "Solaris"
     
   - name: Extraer el Inslador PatrolAgent AIX en el remote Host "{{ ansible_facts['nodename'] }}"
     become: yes
     become_user: patrol
     become_method: su
     become_exe: sudo su -
     unarchive:
       src: /tmp/Base_{{ ansible_facts['os_family'] }}_Patrol_Without.tar.gz
       dest: /tmp
       mode: 0754
       remote_src: yes
     when: ansible_facts['os_family'] == "AIX"

   - name: Extraer el Inslador PatrolAgent Linux en el remote Host "{{ ansible_facts['nodename'] }}"
     become: yes
     become_user: patrol
     become_method: su
     become_exe: sudo su -
     unarchive:
       src: /tmp/Base_{{ ansible_facts['system'] }}_Patrol_Without.tar.gz
       dest: /tmp
       mode: 0754
       remote_src: yes
     when: ansible_facts['system'] == "Linux"

   - name: Extraer el Inslador PatrolAgent Solaris en el remote Host "{{ ansible_facts['nodename'] }}"
     become: yes
     become_user: patrol
     become_method: su
     become_exe: sudo su -
     unarchive:
       src: /tmp/Base_{{ ansible_facts['os_family'] }}_Patrol_Without.tar.gz
       dest: /tmp
       mode: 0754
       remote_src: yes
     when: ansible_facts['os_family'] == "Soladis"

