- name: Validacion pre-requisitos patrol
  block:
   - name: Validar usuario patrol
     stat:
        path: /patrol
     register: directorio_pa     

   - name: Informacion Usuario patrol
     getent:
       database: passwd
       key: patrol
     register: usuario_pa

   - name: Informacion grupo patrol
     getent:
       database: group
       key: grppatro
     register: grupo_pa

   - name: Resultado de la validacion de pre-requisitos de PatrolAgent en el remote Host.
     debug:
       msg: "{{ directorio_pa.uid }},{{ directorio_pa.gid }}"
     when: (directorio_pa.uid == '1301') and (directorio_pa.gid == '1301')
