- name: Crear directorio de UAT
  file:
    path: /tmp/uatgetinfo
    state: directory
    mode: 0700
    
- name: Envio de scripts UAT
  copy:
    src: files/iam_extract_global.sh
    dest: /tmp/uatgetinfo
    mode: 0500
    force: yes

- name: Ejecucion de script UAT
  become: yes
  become_method: sudo
  shell: /tmp/uatgetinfo/iam_extract_global.sh 2>/dev/null -c IBM
  register: status_iam
  failed_when: status_iam.rc not in [ 0, 1 ]
  
- name: Imprime ejecucion del script iam
  debug:
    msg: "{{ status_iam.stdout_lines }}"
